pipeline:
  name: Harness BCP Account Setup
  identifier: Harness_BCP_Account_Setup
  template:
    templateRef: org.Terraform
    versionLabel: 0.0.1
    templateInputs:
      stages:
        - stage:
            identifier: Provisioning
            type: Custom
            variables:
              - name: git_repoName
                type: String
                value: <+input>
              - name: git_branch
                type: String
                value: <+input>
              - name: git_folderPath
                type: String
                value: <+input>
              - name: harness_provisioner_identifier
                type: String
                value: <+input>
              - name: harness_platform_api_key
                type: String
                value: <+input>
              - name: harness_platform_account_id
                type: String
                value: <+input>
              - name: tf_action
                type: String
                value: <+input>
              - name: tf_backend_username
                type: String
                value: <+input>
              - name: tf_backend_password
                type: String
                value: <+input>
              - name: tf_backend_url
                type: String
                value: <+input>
              - name: tf_backend_repo
                type: String
                value: <+input>
              - name: tf_backend_subpath
                type: String
                value: <+input>
  tags: {}
  projectIdentifier: harness_bcp_seed
  orgIdentifier: cristian_lab_org
